#' Calculate Orthogonal B-spline Basis.
#'
#' This function calculates orthogonal B-spline basis.
#'
#' @param bs a matrix, each column of which is the predicted value of the B-spline base at the corresponding point and the B-splines can be generated by \code{\link[splines2]{bSpline}} in \code{splines2} package.
#' @param d the number of continuous variables in initial dataset.
#' @return A matrix, each column of which is the predicted value of the orthogonal B-spline base at the corresponding point.
#' @details The result matrix is obtained by Gram-Schmidt method.
#' @export
#' @examples
#' y <- rnorm(100)
#' bs <- splines2::bSpline(y,degree = 5)
#' # assume that there are 6 continuous variables in initial dataset
#' bar_bs(bs, d = 6)
bar_bs <- function(bs, d){
  brow <- nrow(bs)
  bcol <- ncol(bs)
  result <- matrix(1, brow, bcol)
  for(i in 2:bcol){
    result[, i] <- bs[, i]
    for(j in 1:(i-1)){
      result[, i] <- result[, i]-sum(bs[, i] * result[, j]) * result[, j]/sum(result[, j]^2)
    }
  }
  return(result/sqrt(d))
}
